---
title: |
  | COMP5070_SP2_2023
  | Statistical Programming for Data Science
  | Assignment 2
author: "Enna H"
output: html_notebook
editor_options:
  chunk_output_type: console
---

```{r echo = FALSE, include=FALSE}
# clear all variables, functions, etc
# clean up memory
rm(list=ls())
# clean up memory
gc()
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  fig.width = 8, 
  fig.asp = 0.618, 
  out.width = "80%",
  fig.align = "center", 
  root.dir = "../",
  message = FALSE,
  size = "small"
)
```


```{r warning=FALSE, include=FALSE}
pacman::p_load(tidyverse, gglm)
pacman::p_load(knitr,dplyr,AICcmodavg)
pacman::p_load(inspectdf,tidyr,stringr, stringi,DT)
pacman::p_load(caret,modelr)
pacman::p_load(mlbench,mplot)
pacman::p_load(tidymodels,glmx)
pacman::p_load(skimr,vip,yardstick,ranger,kknn,funModeling,Hmisc)
pacman::p_load(ggplot2,ggpubr,ggthemes,gridExtra,scales)
knitr::opts_chunk$set(message = FALSE)
```


## 1. load data

```{r warning=FALSE, message=FALSE}
# load data
census.data <- read.csv(url("http://bit.ly/infs5100_camden_data"))
```

## 2. data exploration

```{r warning=FALSE, message=FALSE}
# check data
head(census.data)
# get data structure
str(census.data)
```

- Challenge 1.

```{r warning=FALSE, message=FALSE}
# rename column OA to Output_Area
census.data <- rename(census.data, Output_Area = OA)
# check data
names(census.data)
```

## 3. descriptive statistics

```{r warning=FALSE, message=FALSE}
# mean, median, sd, range, quartiles
summary(census.data)
```

```{r warning=FALSE, message=FALSE}
# for unemployment, range
range(census.data$Unemployed)
```


- Challenge 2.

```{r warning=FALSE, message=FALSE}
# use the doBy() package
pacman::p_load(doBy)
```

```{r warning=FALSE, message=FALSE}
# using the summaryBy() function with grouping by the variable Qualification, 
# gives the mean and median for each unique combination of all variables
result <- summaryBy(White_British+Low_Occupancy+Unemployed+Qualification ~ ., 
                    data = census.data, 
                    FUN = function(x) {c(Mean = mean(x, na.rm = TRUE), 
                                         Median = median(x, na.rm = TRUE))})
head(result)
```

```{r warning=FALSE, message=FALSE}
# using the summaryBy() function without grouping by other variables, 
# gives the overall mean and median
result <- summaryBy(White_British+Low_Occupancy+Unemployed+Qualification ~ 1, 
                    data = census.data, 
                    FUN = function(x) {c(Mean = mean(x, na.rm = TRUE), 
                                         Median = median(x, na.rm = TRUE))})
print(result)
```

## 4. Univariate plots

```{r warning=FALSE, message=FALSE}
# Creates a histogram
hist(census.data$Unemployed)
```

```{r warning=FALSE, message=FALSE}
# Creates a histogram, enters more commands about the visualisation
hist(census.data$Unemployed, breaks=20, col= "blue", main="% in full-time employment", xlab="Unemployed")
```

```{r warning=FALSE, message=FALSE}
# box and whisker plots
boxplot(census.data[,2:5], xlab="Percentage")
```

```{r warning=FALSE, message=FALSE}
pacman::p_load(vioplot)
```


```{r warning=FALSE, message=FALSE}
# add names to the plot
vioplot(census.data$Unemployed, census.data$Qualification, 
census.data$White_British, census.data$Low_Occupancy, ylim=c(0,100), col = 
"dodgerblue", rectCol="dodgerblue3", colMed="dodgerblue4")
```

```{r warning=FALSE, message=FALSE}
# add names to the plot
vioplot(census.data$Unemployed, census.data$Qualification, 
census.data$White_British, census.data$Low_Occupancy, ylim=c(0,100), col = 
"dodgerblue", rectCol="dodgerblue3", colMed="dodgerblue4", 
names=c("Unemployed", "Qualifications", "White British", "Occupancy"))
```

```{r warning=FALSE, message=FALSE}
# Open a new png device
png("vioplot.png")

# Create the plot
vioplot(census.data$Unemployed, census.data$Qualification, 
        census.data$White_British, census.data$Low_Occupancy, 
        ylim=c(0,100), 
        col = "dodgerblue", 
        rectCol="dodgerblue3", 
        colMed="dodgerblue4", 
        names=c("Unemployed", "Qualifications", "White British", "Occupancy"))

# Close the png device
dev.off()
```

